### ISSUE TITLE
Segmentation Fault 

### ISSUE THREAD

**Issue by SimonTsungHanKuo** [wuhuikai/FastFCN#56]
我執行以下 command 準備 train model 但是發生 segmentation fault 有人有這個問題嗎 ? 謝謝幫忙 !

run : 
CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py --dataset pcontext     --model encnet --jpu --aux --se-loss     --backbone resnet101 --checkname encnet_res101_pcontext

crashed : 
Using poly LR Scheduler!
Starting Epoch: 0
Total Epoches: 80
  0%|                                                                                           | 0/312 [00:00<?, ?it/s]
=>Epoches 0, learning rate = 0.0010,                 previous best = 0.0000
Segmentation fault

//------------
 Nvidia GPU :  Tesla P100-PCIE 16G x 4 
CPU : GenuineIntel x 18 , Memory 140G totally

**Comment by ZHAOYANANGOGO** [comment]
我执行出现的错误是：
 File "/home/zyn/anaconda3/lib/python3.6/site-packages/encoding/nn/syncbn.py", line 58, in forward
    mean, inv_std = self._slave_pipe.run_slave(_ChildMessage(xsum, xsqsum, N))
AttributeError: 'NoneType' object has no attribute 'run_slave'

看了一下代码，是一个变量没有初始化。有人会解决吗？

**Comment by wuhuikai** [comment]
@ZHAOYANANGOGO Sorry for the late reply. The training script should be conducted with multiple GPUs.

**Comment by wuhuikai** [comment]
@SimonTsungHanKuo Sorry for the late reply. The code is only tested with  Ubuntu 16.04 LTS. We will update the code with the official SyncBN within about two weeks. The problem should be solved then. Stay tuned : )

**Comment by wuhuikai** [comment]
@SimonTsungHanKuo The code in branch `latest` is now ready, which uses official `SyncBatchNorm` and can run on all OS with `PyTorch>=1.1.0`.

**Comment by E18301194** [comment]
Hello, I take the liberty to interrupt you. I ran the old version of this program and found that this bug also appeared. My environment is pytorch 1.2.0 cuda 9.0 python 3.5 and I use multiple GPUs. I still don’t know how to solve this bug. Please help, it is very important to me. thank you

 CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py --dataset ade20k             --model encnet --jpu --aux --se-loss             --backbone resnet50 --checkname encnet_res50_ade20k_train --batch-size 4


Total Epoches: 180
  0%|                                                                                                                                                        | 0/5052 [00:00<?, ?it/s]
=>Epoches 0, learning rate = 0.0025,                 previous best = 0.0000
  0%|                                                                                                                                                        | 0/5052 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 180, in <module>
    trainer.training(epoch)
  File "train.py", line 110, in training
    outputs = self.model(image)
  File "/home/kongmeng/anaconda3/envs/fastfcn1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kongmeng/anaconda3/envs/fastfcn1/lib/python3.6/site-packages/encoding/models/encnet.py", line 33, in forward
    features = self.base_forward(x)
  File "/home/kongmeng/anaconda3/envs/fastfcn1/lib/python3.6/site-packages/encoding/models/base.py", line 55, in base_forward
    x = self.pretrained.conv1(x)
  File "/home/kongmeng/anaconda3/envs/fastfcn1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kongmeng/anaconda3/envs/fastfcn1/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/kongmeng/anaconda3/envs/fastfcn1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kongmeng/anaconda3/envs/fastfcn1/lib/python3.6/site-packages/encoding/nn/syncbn.py", line 58, in forward
    mean, inv_std = self._slave_pipe.run_slave(_ChildMessage(xsum, xsqsum, N))
AttributeError: 'NoneType' object has no attribute 'run_slave'

**Comment by wuhuikai** [comment]
Please use the latest code in the master branch.
